"""change chat_titile to chat_title in chats table

Revision ID: dd7ec3961643
Revises: c7a6380462f6
Create Date: 2026-05-12 19:44:54.434505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd7ec3961643'
down_revision: Union[str, Sequence[str], None] = 'c7a6380462f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('chats', sa.Column('chat_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('chats', 'chat_titile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
